CREATE TABLE IF NOT EXISTS public.personal_cargos (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.personal_cargos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir todo cargos" ON public.personal_cargos FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.personal_cargos (nombre) VALUES
('VERIFICACIÓN DE DOCUMENTOS Y FOTOGRAFÍA'),
('RECEPCIÓN DE EXPEDIENTES DE INGRESANTES'),
('SERVICIO DE CARPETEROS'),
('SERVICIOS DIVERSOS(SOLO VARONES)'),
('SERVICIO DE SEGURIDAD(SOLO VARONES)'),
('SERVICIO DE LIMPIEZA DE PABELLONES Y SSHH'),
('CAMAROGRAFOS'),
('PERIFONISTA')
ON CONFLICT (nombre) DO NOTHING;
